const COACH_MESSAGES_KEY = "borjai:coach:messages:v18";

function coachToken(){try{const s=JSON.parse(localStorage.getItem("borjai:supabase:session:v1")||"null");if(s?.access_token)return s.access_token}catch(_){}if(window.BORJAI_SESSION_TOKEN)return window.BORJAI_SESSION_TOKEN;for(let i=0;i<localStorage.length;i+=1){const k=localStorage.key(i)||"";if(!k.startsWith("sb-")||!k.endsWith("-auth-token"))continue;try{const r=JSON.parse(localStorage.getItem(k)||"null");const t=r?.access_token||r?.currentSession?.access_token||r?.session?.access_token;if(t)return t}catch(_){} }return ""}
function loadMessages(){try{const p=JSON.parse(localStorage.getItem(COACH_MESSAGES_KEY)||"[]");return Array.isArray(p)?p.slice(-40):[]}catch(_){return []}}
function saveMessages(m){try{localStorage.setItem(COACH_MESSAGES_KEY,JSON.stringify(m.slice(-40)))}catch(_) {}}
function cleanAnswer(value){let t=String(value||"");t=t.replace(/<think>[\s\S]*?<\/think>/gi,"").replace(/<analysis>[\s\S]*?<\/analysis>/gi,"").replace(/<reasoning>[\s\S]*?<\/reasoning>/gi,"").replace(/<think>[\s\S]*$/gi,"").replace(/<analysis>[\s\S]*$/gi,"").replace(/<reasoning>[\s\S]*$/gi,"").replace(/^[\s\S]*<\/think>/gi,"").replace(/^[\s\S]*<\/analysis>/gi,"").replace(/^[\s\S]*<\/reasoning>/gi,"");return t.replace(/^\s*```(?:markdown|md|text)?\s*/i,"").replace(/\s*```\s*$/i,"").trim()}
function formatAnswer(value){const safe=cleanAnswer(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));return safe.replace(/^###\s+(.+)$/gm,"<strong>$1</strong>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/^[-•]\s+/gm,"• ").replace(/\n/g,"<br>")}
function contextFromState(state){
  const transactions=Array.isArray(state?.transactions)?state.transactions:[];
  const accounts=Array.isArray(state?.accounts)?state.accounts:[];
  const assets=Array.isArray(state?.assets)?state.assets:[];
  const debts=Array.isArray(state?.debts)?state.debts:(Array.isArray(state?.liabilities)?state.liabilities:[]);
  const goals=Array.isArray(state?.goals)?state.goals:[];
  const investments=Array.isArray(state?.investments)?state.investments:[];
  const snapshots=Array.isArray(state?.snapshots)?state.snapshots:[];
  const now=new Date();const month=now.toISOString().slice(0,7);
  const monthTx=transactions.filter(t=>String(t.date||"").slice(0,7)===month);
  const income=monthTx.filter(t=>t.type==="income"||Number(t.amount||0)>0).reduce((s,t)=>s+Math.abs(Number(t.amount||0)),0);
  const expense=monthTx.filter(t=>t.type==="expense"||t.type==="fee"||Number(t.amount||0)<0).reduce((s,t)=>s+Math.abs(Number(t.amount||0)),0);
  const savings=income-expense;
  const byCategory={};monthTx.filter(t=>Number(t.amount||0)<0||["expense","fee"].includes(t.type)).forEach(t=>{const c=t.category||"Otros";byCategory[c]=(byCategory[c]||0)+Math.abs(Number(t.amount||0))});
  const daysElapsed=Math.max(1,now.getDate());
  const dailyExpense=expense/daysElapsed;
  const daysInMonth=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();
  const projectedExpense=dailyExpense*daysInMonth;
  const netWorth=accounts.reduce((s,a)=>s+Number(a.balance||a.value||0),0)+assets.reduce((s,a)=>s+Number(a.value||a.balance||0),0)-debts.reduce((s,d)=>s+Number(d.balance||d.outstandingBalance||d.value||0),0);
  return {asOf:now.toISOString().slice(0,10),profile:state?.profile||{},netWorth,monthly:{income,expense,savings,savingsRate:income? savings/income: null,dailyExpense,projectedExpense},spendingByCategory:Object.fromEntries(Object.entries(byCategory).sort((a,b)=>b[1]-a[1])),accounts,assets,debts,investments,goals,snapshots: snapshots.slice(-370),recentTransactions:transactions.slice(-500)};
}
async function askCoach(question){const token=coachToken();if(!token)throw new Error("No encuentro la sesión de Supabase. Recarga la aplicación e inténtalo de nuevo.");const sr=await fetch("/api/state",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const sp=await sr.json().catch(()=>({}));if(!sr.ok||!sp.state)throw new Error(sp?.error||"No se pudo cargar tu situación financiera desde Supabase.");const context=contextFromState(sp.state);const response=await fetch("/api/coach-v18",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({question,context,useWeb:true})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||"No se pudo consultar el asistente IA.");return payload}
function messageNode(message){const row=document.createElement("div");row.className="chat-message"+(message.role==="user"?" user":"");row.innerHTML=(message.role==="assistant"?'<div class="chat-avatar coach-avatar-fallback" aria-hidden="true"><span>B</span></div>':"")+'<div class="chat-bubble">'+(message.loading?"Estoy analizando tus datos…":(message.html?message.html:formatAnswer(message.text)))+"</div>";return row}
function renderPersistentChat(){const node=document.getElementById("messages");if(!node)return;const messages=loadMessages();node.innerHTML="";if(!messages.length){node.appendChild(messageNode({role:"assistant",text:"Hola, Borja 👋 Soy tu asistente financiero. Puedo analizar tus gastos, ahorro, patrimonio, inversiones y objetivos con los datos reales de tu aplicación."}));return}messages.forEach(m=>node.appendChild(messageNode(m)));node.scrollTop=node.scrollHeight}
function addMessage(role,text,extra={}){const messages=loadMessages(),message={role,text:cleanAnswer(text),...extra};messages.push(message);saveMessages(messages);const node=document.getElementById("messages");if(node){node.appendChild(messageNode(message));node.scrollTop=node.scrollHeight}return message}
function setLoading(on){const input=document.querySelector('#chat-form input[name="question"]'),button=document.querySelector('#chat-form button');if(input)input.disabled=on;if(button)button.disabled=on}
async function submitQuestion(question){const value=String(question||"").trim();if(!value)return;addMessage("user",value);const greeting=/^(hola|holaa+|buenas|buenos días|buenas tardes|buenas noches|hey|hello)\s*[!.?]*$/i.test(value);if(greeting){addMessage("assistant","¡Hola, Borja! 👋 Estoy listo. Puedes preguntarme por tus gastos, ahorro, inversiones, patrimonio u objetivos.");return}setLoading(true);const node=document.getElementById("messages"),loading=messageNode({role:"assistant",loading:true});if(node){node.appendChild(loading);node.scrollTop=node.scrollHeight}try{const result=await askCoach(value);loading.remove();addMessage("assistant",result.answer||"No se obtuvo respuesta.")}catch(error){loading.remove();addMessage("assistant",`No pude completar el análisis: ${error.message}`)}finally{setLoading(false);document.querySelector('#chat-form input[name="question"]')?.focus()}}
function enhanceCoach(){const view=document.querySelector(".coach-view");if(!view)return;document.getElementById("ai-council-banner")?.remove();document.querySelector(".coach-context")?.remove();if(view.dataset.coachV18Enhanced==="1")return;view.dataset.coachV18Enhanced="1";view.classList.add("coach-v18");renderPersistentChat()}
document.addEventListener("click",event=>{const action=event.target.closest?.('[data-action="ask"]');if(!action||!document.querySelector(".coach-view"))return;event.preventDefault();event.stopImmediatePropagation();submitQuestion(action.dataset.q||"")},true);
document.addEventListener("submit",event=>{if(event.target?.id!=="chat-form")return;event.preventDefault();event.stopImmediatePropagation();const input=event.target.elements.question,value=input?.value||"";if(input)input.value="";submitQuestion(value)},true);
const observer=new MutationObserver(enhanceCoach);observer.observe(document.body,{childList:true,subtree:true});enhanceCoach();
