const num=(v)=>Number.isFinite(Number(v))?Number(v):0;
const ym=(v)=>String(v||"").slice(0,7);
const monthKey=(d=new Date())=>d.toISOString().slice(0,7);
const abs=(v)=>Math.abs(num(v));
const normalizeName=(v)=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/\s+/g," ");
const dateValue=(v)=>new Date(`${String(v||"").slice(0,10)}T12:00:00`).getTime();
export function classifyTransactions(transactions=[]){return{expenses:transactions.filter(t=>["expense","fee"].includes(t.type)),income:transactions.filter(t=>["income","dividend"].includes(t.type)),transfers:transactions.filter(t=>["transfer","internal_transfer"].includes(t.type))};}
export function monthlyTotals(transactions=[],month=monthKey()){const g=classifyTransactions(transactions);const expenses=g.expenses.filter(t=>ym(t.date)===month).reduce((s,t)=>s+abs(t.amount),0);const income=g.income.filter(t=>ym(t.date)===month).reduce((s,t)=>s+abs(t.amount),0);return{expenses,income,net:income-expenses};}
export function balances(data={}){const accounts=data.accounts||[],assets=data.assets||[],liabilities=data.liabilities||data.debts||[];const liquid=accounts.reduce((s,a)=>s+num(a.current_balance??a.balance),0),investedAssets=assets.reduce((s,a)=>s+num(a.current_value??a.value),0),debt=liabilities.reduce((s,l)=>s+num(l.outstanding_balance??l.current_balance??l.balance),0);return{liquid,investedAssets,debt,netWorth:liquid+investedAssets-debt};}
export function historicalMonthlyExpenses(transactions=[],months=3){const out=[],d=new Date();d.setDate(1);for(let i=0;i<months;i++){const key=monthKey(d);out.push({month:key,...monthlyTotals(transactions,key)});d.setMonth(d.getMonth()-1);}return out;}
export function recurringPayments(transactions=[]){const groups=new Map();for(const t of classifyTransactions(transactions).expenses){const name=normalizeName(t.merchant||t.description||"Movimiento"),amount=abs(t.amount);if(!name||!amount||!t.date)continue;const list=groups.get(name)||[];list.push({date:String(t.date).slice(0,10),amount,original:t});groups.set(name,list);}return[...groups.values()].map(list=>{list.sort((a,b)=>dateValue(a.date)-dateValue(b.date));if(list.length<2)return null;const gaps=[];for(let i=1;i<list.length;i++){const gap=(dateValue(list[i].date)-dateValue(list[i-1].date))/86400000;if(gap>0)gaps.push(gap);}if(!gaps.length)return null;const avgGap=gaps.reduce((s,v)=>s+v,0)/gaps.length;if(avgGap<20||avgGap>40)return null;const avgAmount=list.reduce((s,v)=>s+v.amount,0)/list.length,last=list.at(-1),next=new Date(dateValue(last.date)+avgGap*86400000);return{merchant:last.original.merchant||last.original.description||"Movimiento",category:last.original.category_name||"Otros",amount:avgAmount,avgGap,next,occurrences:list.length};}).filter(Boolean).sort((a,b)=>b.amount-a.amount);}
export function anomalies(transactions=[],month=monthKey()){const groups=new Map();for(const t of classifyTransactions(transactions).expenses){const key=normalizeName(t.category_name||"Otros"),arr=groups.get(key)||[];arr.push({date:t.date,amount:abs(t.amount),merchant:t.merchant||t.description||"Movimiento",category:t.category_name||"Otros"});groups.set(key,arr);}const out=[];groups.forEach(arr=>{const hist=arr.filter(x=>ym(x.date)!==month).map(x=>x.amount);if(hist.length<3)return;const avg=hist.reduce((s,v)=>s+v,0)/hist.length;arr.filter(x=>ym(x.date)===month&&x.amount>Math.max(avg*2.2,avg+50)).forEach(x=>out.push({...x,average:avg}));});return out.sort((a,b)=>b.amount-a.amount).slice(0,10);}
export function duplicates(transactions=[]){const seen=new Map(),out=[];for(const t of transactions){const account=String(t.account_id??t.account_legacy_id??"");const key=[String(t.date||"").slice(0,10),account,String(t.currency||"EUR").toUpperCase(),String(t.type||""),Math.round(num(t.amount)*100),normalizeName(t.merchant||t.description)].join("|");if(seen.has(key)){const first=seen.get(key);if(!(first.id&&t.id&&first.id===t.id))out.push({first,duplicate:t});}else seen.set(key,t);}return out;}
export function healthScore(data={},month=monthKey()){const totals=monthlyTotals(data.transactions||[],month),b=balances(data),history=historicalMonthlyExpenses(data.transactions||[],3).slice(1),avgExpense=history.length?history.reduce((s,x)=>s+x.expenses,0)/history.length:totals.expenses,savingsRate=totals.income>0?Math.max(0,totals.net/totals.income):0,monthsLiquidity=avgExpense>0?b.liquid/avgExpense:0,debtRatio=b.netWorth>0?b.debt/b.netWorth:0;if(!(data.transactions||[]).length&&!b.liquid&&!b.investedAssets&&!b.debt)return{score:0,savingsRate,monthsLiquidity,debtRatio,label:"Sin datos"};let score=50;score+=Math.min(25,savingsRate*100);score+=Math.min(15,monthsLiquidity*4);score-=Math.min(20,debtRatio*30);return{score:Math.max(0,Math.min(100,Math.round(score))),savingsRate,monthsLiquidity,debtRatio,label:"Calculada con datos reales"};}
export function affordability(data={},amount=0,now=new Date()){const b=balances(data),purchase=Math.max(0,num(amount)),today=dateValue(now.toISOString().slice(0,10)),recurring=recurringPayments(data.transactions||[]),expectedNext=recurring.filter(r=>dateValue(r.next)>=today).reduce((s,r)=>s+r.amount,0),available=b.liquid,after=available-purchase;const hist=historicalMonthlyExpenses(data.transactions||[],3).slice(1).map(x=>x.expenses).filter(Boolean),avg=hist.length?hist.reduce((s,v)=>s+v,0)/hist.length:monthlyTotals(data.transactions||[]).expenses,threshold=Math.max(0,avg*1.5),bufferAfter=after-expectedNext;return{gross:b.liquid,recurringReserve:expectedNext,available,after,bufferAfter,affordable:after>=threshold&&bufferAfter>=0,caution:after>=0&&bufferAfter<0?true:after>=0&&after<threshold};}
export const financialEngine={classifyTransactions,monthlyTotals,balances,historicalMonthlyExpenses,recurringPayments,anomalies,duplicates,healthScore,affordability};
