export const CATEGORIES = ["Vivienda","Alimentacion","Restaurantes","Gasolina","Transporte","Ocio","Compras","Suscripciones","Viajes","Salud","Seguros","Formacion","Tecnologia","Inversiones","Criptomonedas","Impuestos","Otros"];
function clean(n){return String(n??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function iso(d){return d.toISOString().slice(0,10)}
export function classify(text){const n=clean(text);const rules=[["mercadona|carrefour|lidl|alcampo","Alimentacion"],["restaurante|glovo|just eat|bar |cafe","Restaurantes"],["repsol|cepsa|shell","Gasolina"],["uber|cabify|renfe|metro","Transporte"],["netflix|spotify|icloud|adobe|youtube|hbo|disney","Suscripciones"],["alquiler|hipoteca|comunidad","Vivienda"],["zara|amazon|ikea|decathlon","Compras"],["mapfre|mutua|adeslas|sanitas","Seguros"],["farmacia|dent|medic","Salud"],["hacienda|aeat|impuesto|tribut","Impuestos"],["myinvestor|indexa|degiro|ibkr|interactive brokers","Inversiones"],["coinbase|binance|kraken","Criptomonedas"]];const rule=rules.find(r=>new RegExp(r[0]).test(n));return rule?rule[1]:"Otros"}
export function parseNumber(v){if(v==null||v==="")return NaN;let s=String(v).trim().replace(/[€$£\s]/g,"");const negative=/^\(.*\)$/.test(s)||/-$/.test(s);s=s.replace(/[()]/g,"").replace(/-$/,""),lastComma=s.lastIndexOf(","),lastDot=s.lastIndexOf(".");if(lastComma>=0&&lastDot>=0){if(lastComma>lastDot)s=s.replace(/\./g,"").replace(",",".");else s=s.replace(/,/g,"")}else if(lastComma>=0){const decimals=s.length-lastComma-1;s=decimals<=2?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"")}else if((s.match(/\./g)||[]).length>1)s=s.replace(/\./g,"");const n=Number(s);return Number.isFinite(n)?negative?-Math.abs(n):n:NaN}
export function csvLine(line,delim){const out=[];let v="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===delim&&!q){out.push(v.trim());v=""}else v+=c}out.push(v.trim());return out}
function detectDelimiter(line){const candidates=[";",",","\t"];return candidates.map(d=>[d,csvLine(line,d).length]).sort((a,b)=>b[1]-a[1])[0][0]}
export function csvDate(v,fallbackDate){const x=String(v??"").trim();if(/^\d{4}-\d{2}-\d{2}$/.test(x))return x;const m=x.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})$/);if(m)return(m[3].length===2?"20"+m[3]:m[3])+"-"+m[2].padStart(2,"0")+"-"+m[1].padStart(2,"0");const parsed=new Date(x);return Number.isNaN(parsed.getTime())?iso(fallbackDate||new Date()):iso(parsed)}
export function parseCsv(text,file="CSV",defaultAccountId,fallbackDate){const lines=String(text??"").replace(/^\uFEFF/,"").split(/\r?\n/).filter(l=>l.trim());if(lines.length<2)throw new Error("El CSV necesita encabezados y al menos un movimiento.");const delim=detectDelimiter(lines[0]);const headers=csvLine(lines[0],delim).map(clean);const find=options=>headers.findIndex(h=>options.some(o=>h===o||h.includes(o)));const d=find(["fecha","date","dia"]),m=find(["concepto","descripcion","detalle","merchant","comercio","nombre","beneficiario"]),a=find(["importe","amount","cantidad","valor","monto","movimiento"]),debit=find(["cargo","debe","debit","gasto"]),credit=find(["abono","haber","credit","ingreso"]),c=find(["categoria","category"]);if(m<0)throw new Error("No encuentro la columna de concepto/descripcion.");if(a<0&&debit<0&&credit<0)throw new Error("No encuentro una columna de importe, cargo o abono.");const rows=[];for(const line of lines.slice(1)){const v=csvLine(line,delim),merchant=v[m]||"Movimiento importado";let amount=a>=0?parseNumber(v[a]):NaN;if(!Number.isFinite(amount)){const outflow=debit>=0?parseNumber(v[debit]):NaN,inflow=credit>=0?parseNumber(v[credit]):NaN;if(Number.isFinite(inflow)&&inflow!==0)amount=Math.abs(inflow);else if(Number.isFinite(outflow)&&outflow!==0)amount=-Math.abs(outflow)}if(!Number.isFinite(amount))continue;const rawCategory=c>=0?String(v[c]||"").trim():"",category=CATEGORIES.includes(rawCategory)?rawCategory:classify(merchant);rows.push({date:d>=0?csvDate(v[d],fallbackDate):iso(fallbackDate||new Date()),merchant,description:"Importado desde "+file,amount,type:amount>=0?"income":"expense",category,accountId:defaultAccountId})}if(!rows.length)throw new Error("No se encontraron movimientos financieros válidos en el CSV.");return rows.slice(0,5000)}
